---
name: Trigger PKGBUILD Test

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate a Pull Request
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: 'pkgbuild'
          pkgname: 'opencore-efi'


      - name: Validate binary
        id: validate-binary
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: 'run'
          pkgname: 'opencore-efi'
          command: 'pacman -Q | grep opencore-efi && sudo pacman -Rcns opencore-efi --noconfirm'

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3.0.0
        with:
          file_or_dir: .github/workflows/ci.yml
